#include <bits/stdc++.h>

using namespace std;

int main() {
printf("97 e a");
cout << endl;
printf("98 e b");
cout << endl;
printf("99 e c");
cout << endl;
printf("100 e d");
cout << endl;
printf("101 e e");
cout << endl;
printf("102 e f");
cout << endl;
printf("103 e g");
cout << endl;
printf("104 e h");
cout << endl;
printf("105 e i");
cout << endl;
printf("106 e j");
cout << endl;
printf("107 e k");
cout << endl;
printf("108 e l");
cout << endl;
printf("109 e m");
cout << endl;
printf("110 e n");
cout << endl;
printf("111 e o");
cout << endl;
printf("112 e p");
cout << endl;
printf("113 e q");
cout << endl;
printf("114 e r");
cout << endl;
printf("115 e s");
cout << endl;
printf("116 e t");
cout << endl;
printf("117 e u");
cout << endl;
printf("118 e v");
cout << endl;
printf("119 e w");
cout << endl;
printf("120 e x");
cout << endl;
printf("121 e y");
cout << endl;
printf("122 e z");
cout << endl;
	return 0;
}
